title: Haptically Speaking
author: Floyd Hightower <https://github.com/fhightower>
email: hapticallyspeaking@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website for Haptically Speaking, a business dedicated to making the universe accessible to those with visual impairments.

sass:
    style: compressed